### ISSUE TITLE
can't find validateMessage after updating to v2.10.0

### ISSUE THREAD

**Issue by travi** [kentcdodds/validate-commit-msg#63]
looks like this is likely related to [moving validateMessage to lib](https://github.com/kentcdodds/validate-commit-msg/pull/61)

I haven't had a chance to dig deeper than reverting back to v2.9.0, but wanted to at least give you a heads up about the issue. 

```
Found '/Users/admin/development/travi.org/admin/components/.nvmrc' with version <v7.4>
Now using node v7.4.0 (npm v4.0.5)
module.js:472
    throw err;
    ^

Error: Cannot find module './lib/validateMessage'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/admin/development/travi.org/admin/components/node_modules/validate-commit-msg/index.js:3:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

husky - commit-msg hook failed (add --no-verify to bypass)

/Users/admin/.nvm/versions/node/v7.4.0/lib/node_modules/commitizen/dist/cli/strategies/git-cz.js:102
        throw error;
        ^

Error: git exited with error code 1
    at ChildProcess.<anonymous> (/Users/admin/.nvm/versions/node/v7.4.0/lib/node_modules/commitizen/dist/git/commit.js:50:26)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by kentcdodds** [comment]
Thanks for the quick report! The new version should be auto-released in a moment. Was a simple oversight: ea45ffd

**Comment by travi** [comment]
thanks for the quick fix, too! 

also, thanks for your work on tools that encourage auto-releasing packages. this package in particular has become an important part of my team's pipeline, to simplify our own use of semantic-release. paired with greenkeeper and [greenkeeper-keeper](https://github.com/greenkeeper-keeper/meta), the combo can be powerful.

**Comment by kentcdodds** [comment]
That's awesome to hear! I'm so glad that it's been helpful to you!
